/**
* @description - List of all possible actions as ENNUM
* @enum
*/
export const ACTIONS_ENUM = {
  'RECIEVE_DECK_LIST' : 'RECIEVE_DECK_LIST',
  'RECIEVE_CARD_LIST' : 'RECIEVE_CARD_LIST',
  'GET_DECK_LIST' : 'GET_DECK_LIST',
  'GET_CARD_LIST' : 'GET_CARD_LIST',
  'ADD_CARD' : 'ADD_CARD',
  'ADD_DECK' : 'ADD_DECK',
  'DELETE_CARD' : 'DELETE_CARD',
  'DELETE_DECK' : 'DELETE_DECK',
  'RECIEVE_SCORE' : 'RECIEVE_SCORE',
}
